// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.11.4
// source: momo .proto

package momo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MomoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *MomoRequest) Reset() {
	*x = MomoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_momo__proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MomoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MomoRequest) ProtoMessage() {}

func (x *MomoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_momo__proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MomoRequest.ProtoReflect.Descriptor instead.
func (*MomoRequest) Descriptor() ([]byte, []int) {
	return file_momo__proto_rawDescGZIP(), []int{0}
}

func (x *MomoRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MomoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *MomoReply) Reset() {
	*x = MomoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_momo__proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MomoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MomoReply) ProtoMessage() {}

func (x *MomoReply) ProtoReflect() protoreflect.Message {
	mi := &file_momo__proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MomoReply.ProtoReflect.Descriptor instead.
func (*MomoReply) Descriptor() ([]byte, []int) {
	return file_momo__proto_rawDescGZIP(), []int{1}
}

func (x *MomoReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_momo__proto protoreflect.FileDescriptor

var file_momo__proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6d, 0x6f, 0x6d, 0x6f, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d,
	0x6f, 0x6d, 0x6f, 0x22, 0x27, 0x0a, 0x0b, 0x4d, 0x6f, 0x6d, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x25, 0x0a, 0x09,
	0x4d, 0x6f, 0x6d, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x32, 0x38, 0x0a, 0x06, 0x42, 0x79, 0x65, 0x62, 0x79, 0x65, 0x12, 0x2e, 0x0a,
	0x06, 0x53, 0x61, 0x79, 0x42, 0x79, 0x65, 0x12, 0x11, 0x2e, 0x6d, 0x6f, 0x6d, 0x6f, 0x2e, 0x4d,
	0x6f, 0x6d, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x6d, 0x6f, 0x6d,
	0x6f, 0x2e, 0x4d, 0x6f, 0x6d, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_momo__proto_rawDescOnce sync.Once
	file_momo__proto_rawDescData = file_momo__proto_rawDesc
)

func file_momo__proto_rawDescGZIP() []byte {
	file_momo__proto_rawDescOnce.Do(func() {
		file_momo__proto_rawDescData = protoimpl.X.CompressGZIP(file_momo__proto_rawDescData)
	})
	return file_momo__proto_rawDescData
}

var file_momo__proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_momo__proto_goTypes = []interface{}{
	(*MomoRequest)(nil), // 0: momo.MomoRequest
	(*MomoReply)(nil),   // 1: momo.MomoReply
}
var file_momo__proto_depIdxs = []int32{
	0, // 0: momo.Byebye.SayBye:input_type -> momo.MomoRequest
	1, // 1: momo.Byebye.SayBye:output_type -> momo.MomoReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_momo__proto_init() }
func file_momo__proto_init() {
	if File_momo__proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_momo__proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MomoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_momo__proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MomoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_momo__proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_momo__proto_goTypes,
		DependencyIndexes: file_momo__proto_depIdxs,
		MessageInfos:      file_momo__proto_msgTypes,
	}.Build()
	File_momo__proto = out.File
	file_momo__proto_rawDesc = nil
	file_momo__proto_goTypes = nil
	file_momo__proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ByebyeClient is the client API for Byebye service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ByebyeClient interface {
	SayBye(ctx context.Context, in *MomoRequest, opts ...grpc.CallOption) (*MomoReply, error)
}

type byebyeClient struct {
	cc grpc.ClientConnInterface
}

func NewByebyeClient(cc grpc.ClientConnInterface) ByebyeClient {
	return &byebyeClient{cc}
}

func (c *byebyeClient) SayBye(ctx context.Context, in *MomoRequest, opts ...grpc.CallOption) (*MomoReply, error) {
	out := new(MomoReply)
	err := c.cc.Invoke(ctx, "/momo.Byebye/SayBye", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ByebyeServer is the server API for Byebye service.
type ByebyeServer interface {
	SayBye(context.Context, *MomoRequest) (*MomoReply, error)
}

// UnimplementedByebyeServer can be embedded to have forward compatible implementations.
type UnimplementedByebyeServer struct {
}

func (*UnimplementedByebyeServer) SayBye(context.Context, *MomoRequest) (*MomoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayBye not implemented")
}

func RegisterByebyeServer(s *grpc.Server, srv ByebyeServer) {
	s.RegisterService(&_Byebye_serviceDesc, srv)
}

func _Byebye_SayBye_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MomoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ByebyeServer).SayBye(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/momo.Byebye/SayBye",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ByebyeServer).SayBye(ctx, req.(*MomoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Byebye_serviceDesc = grpc.ServiceDesc{
	ServiceName: "momo.Byebye",
	HandlerType: (*ByebyeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayBye",
			Handler:    _Byebye_SayBye_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "momo .proto",
}
